ConferenceManager/Controllers/AttendeeController.cs
using ConferenceManager.Models.Entities;
using ConferenceManager.Services.DataAccess;
using ConferenceManager.Services.DataAccess.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ConferenceManager.Controllers
{
    public class AttendeeController : Controller
    {
        private IConferenceManagerRepository<Attendee> context;
        private ISession session { get; set; }

        public AttendeeController(IConferenceManagerRepository<Attendee> ctx, IHttpContextAccessor accessor)
        {
            context = ctx;
            session = accessor.HttpContext.Session;
        }

        [Route("[controller]s")]
        public ViewResult ListAttendees()
        {
            var attendees = context.List(new QueryOptions<Attendee>
            {
                OrderBy = a => a.LastName
            });
            return View(attendees);
        }

        [Route("[controller]/delete")]
        [HttpGet]
        public IActionResult DeleteAttendee(int id)
        {
            var attendee = context.Get(id);
            return View(attendee);
        }

        [HttpPost]
        public IActionResult DeleteAttendee(Attendee attendee)
        {
            context.Delete(attendee);
            context.Save();
            return RedirectToAction("ListAttendees");
        }

        [Route("[controller]/edit")]
        [HttpGet]
        public ViewResult EditAttendee(int id)
        {
            var a = context.Get(id);
            return View(a);
        }

        [Route("[controller]/add")]
        [HttpGet]
        public ViewResult AddAttendee()
        {
            return View(new Attendee());
        }

        [HttpPost]
        public IActionResult SaveAttendee(Attendee attendee)
        {
            string message;
            if (ModelState.IsValid)
            {
                if (attendee.ID == 0)
                {
                    context.Insert(attendee);
                    message = attendee.FullName + " was added.";
                }
                else
                {
                    context.Update(attendee);
                    message = attendee.FullName + " was updated.";
                }
                context.Save();
                TempData["message"] = message;
                return RedirectToAction("ListAttendees");
            }
            else
            {
                return View(attendee);
            }
        }

        [Route("[controller]/view")]
        public ViewResult ViewAttendee(int id)
        {
            var a = context.Get(id);
            return View(a);
        }
    }
}

ConferenceManager/Controllers/ConferenceController.cs
using ConferenceManager.Models.Entities;
using ConferenceManager.Services.DataAccess;
using ConferenceManager.Services.DataAccess.Interfaces;
using ConferenceManager.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace ConferenceManager.Controllers
{
    public class ConferenceController : Controller
    {
        private IConferenceManagerUnit context;
        private ISession session { get; set; }

        public ConferenceController(IConferenceManagerUnit ctx, IHttpContextAccessor accessor)
        {
            context = ctx;
            session = accessor.HttpContext.Session;
        }

        //Dashboard view for all conferences
        [Route("[controller]s/dashboard")]
        [HttpGet]
        public ViewResult Dashboard()
        {
            var c = context.Conferences.List(new QueryOptions<Conference>
            {
                OrderBy = c => c.Name
            });
            return View(c);
        }

        //View details of one conference
        [Route("[controller]/view")]
        public ViewResult ViewConference(int conferenceID)
        {
            IEnumerable<ConferenceVenue> tempV = context.ConferenceVenues.List(new QueryOptions<ConferenceVenue>
            {
                Where = cv => cv.ConferenceID == conferenceID
            });

            IEnumerable<ConferenceAttendee> tempA = context.ConferenceAttendees.List(new QueryOptions<ConferenceAttendee>
            {
                Where = ca => ca.ConferenceID == conferenceID
            });

            IEnumerable<Venue> v = from i in tempV select i.Venue;
            IEnumerable<Attendee> a = from i in tempA select i.Attendee;


            ConferenceViewModel model = new ConferenceViewModel()
            {
                Conference = context.Conferences.Get(conferenceID),
                Venues = v,
                Attendees = a
            };
            return View(model);
        }

        //List all conferences in database
        [Route("[controller]s")]
        public ViewResult ListConferences()
        {
            IEnumerable<Conference> c = context.Conferences.List();
            return View(c);
        }


        //Delete a conference. not implemented in views due to database concerns (cascading deletes untested)
        [Route("[controller]/delete")]
        [HttpGet]
        public ViewResult DeleteConference(int conferenceID)
        {
            var c = context.Conferences.Get(conferenceID);
            return View(c);
        }

        //Delete a conference. not implemented in views due to database concerns (cascading deletes untested)
        [HttpPost]
        public RedirectToActionResult DeleteConference(Conference conference)
        {
            context.Conferences.Delete(conference);
            context.SaveChanges();
            TempData["message"] = conference.Name + " was deleted";
            return RedirectToAction("ListConferences");
        }

        [Route("[controller]/edit")]
        [HttpGet]
        public ViewResult EditConference(int conferenceID)
        {
            var a = context.Conferences.Get(conferenceID);
            return View(a);
        }

        [Route("[controller]/add")]
        [HttpGet]
        public ViewResult AddConference()
        {
            return View(new Conference());
        }

        [HttpPost]
        public IActionResult SaveConference(Conference conference)
        {
            if (ModelState.IsValid)
            {
                if (conference.ID == 0)
                {
                    context.Conferences.Insert(conference);
                    TempData["message"] = conference.Name + " was added";
                }
                else
                {
                    context.Conferences.Update(conference);
                    TempData["message"] = conference.Name + " was updated";
                }
                context.SaveChanges();
                return RedirectToAction("ListConferences");
            }
            else
            {
                return View(conference);
            }
        }
    }
}

ConferenceManager/Controllers/RoomController.cs
using ConferenceManager.Models.Entities;
using ConferenceManager.Services.DataAccess.Interfaces;
using ConferenceManager.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ConferenceManager.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoomController : Controller
    {
        private IConferenceManagerUnit context;
        private ISession session { get; set; }

        public RoomController(IConferenceManagerUnit ctx, IHttpContextAccessor accessor)
        {
            context = ctx;
            session = accessor.HttpContext.Session;
        }

        [Route("[controller]s")]
        public ViewResult ListRooms()
        {
            IEnumerable<Room> r = context.Rooms.List();
            return View(r);
        }

        [Route("[controller]/delete")]
        [HttpGet]
        public ViewResult DeleteRoom(int id)
        {
            var r = context.Rooms.Get(id);
            return View(r);
        }

        [HttpPost]
        public RedirectToActionResult DeleteRoom(Room room)
        {
            context.Rooms.Delete(room);
            context.SaveChanges();
            TempData["message"] = room.Name + "was deleted";
            return RedirectToAction("ListRooms");
        }

        [Route("[controller]/edit")]
        [HttpGet]
        public ViewResult EditRoom(int id)
        {
            Room r = context.Rooms.Get(id);
            var model = new RoomViewModel
            {
                Room = r,
                Venue = context.Venues.Get(r.VenueID),
                Venues = context.Venues.List()
            };
            return View(model);
        }

        [Route("[controller]/add")]
        [HttpGet]
        public ViewResult AddRoom()
        {
            var model = new RoomViewModel
            {
                Room = new Room(),
                Venue = new Venue(),
                Venues = context.Venues.List()
            };
            return View(model);
        }

        [Route("[controller]/save")]
        [HttpPost]
        public IActionResult SaveRoom(Room Room)
        {
            if (Room.ID == 0)
            {
                context.Rooms.Insert(Room);
                context.SaveChanges();
                TempData["message"] = Room.Name + "was added to " + Room.Venue.Name;
            }
            else
            {
                context.Rooms.Update(Room);
                context.SaveChanges();
                TempData["message"] = Room.Name + "was updated";
            }
            return RedirectToAction("ListRooms");
        }

        [Route("[controller]/view")]
        public ViewResult ViewRoom(int id)
        {
            var r = context.Rooms.Get(id);
            return View(r);
        }
    }
}

ConferenceManager/Controllers/VenueController.cs
using ConferenceManager.Models.Entities;
using ConferenceManager.Services.DataAccess.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ConferenceManager.Controllers
{
    [Authorize(Roles = "admin")]
    public class VenueController : Controller
    {
        private IConferenceManagerUnit context;
        private ISession session { get; set; }

        public VenueController(IConferenceManagerUnit ctx, IHttpContextAccessor accessor)
        {
            context = ctx;
            session = accessor.HttpContext.Session;
        }

        [Route("[controller]s")]
        public ViewResult ListVenues()
        {
            var v = context.Venues.List();
            return View(v);
        }

        [Route("[controller]/delete")]
        [HttpGet]
        public ViewResult DeleteVenue(int id)
        {
            var v = context.Venues.Get(id);
            return View(v);
        }


        [HttpPost]
        public RedirectToActionResult DeleteVenue(Venue venue)
        {
            context.Venues.Delete(venue);
            context.SaveChanges();
            TempData["message"] = venue.Name + "was deleted";
            return RedirectToAction("ListVenues");
        }

        [Route("[controller]/edit")]
        [HttpGet]
        public ViewResult EditVenue(int id)
        {
            var a = context.Venues.Get(id);
            return View(a);
        }

        [Route("[controller]/add")]
        [HttpGet]
        public ViewResult AddVenue()
        {
            return View(new Venue());
        }


        [HttpPost]
        public IActionResult SaveVenue(Venue venue)
        {
            if (venue.ID == 0)
            {
                context.Venues.Insert(venue);
                context.SaveChanges();
                TempData["message"] = venue.Name + "was saved";
            }
            else
            {
                context.Venues.Update(venue);
                context.SaveChanges();
                TempData["message"] = venue.Name + "was updated";
            }
            return RedirectToAction("ListVenues");
        }

        [Route("[controller]/view")]
        public ViewResult ViewVenue(int id)
        {
            Venue v = context.Venues.Get(id);
            return View(v);
        }
    }
}

ConferenceManager/Views/Shared/_LandingPageLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <link rel="icon" type="image/x-icon" href="~/assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="~/assets/img/logos//ConferenceManagerLogo.png" alt="" /></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ml-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Services</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team">Team</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
        <div class="container">
            <div class="masthead-subheading">Conference Manager Pro</div>
            <div class="masthead-heading text-uppercase">Meeting management platform</div>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger"
               asp-action="Login" asp-controller="Account">Let's get started!</a>
        </div>
    </header>
    <div>
        @RenderBody()
    </div>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-left">Copyright © Your Website 2020</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-right">
                    <a class="mr-3" href="#!">Privacy Policy</a>
                    <a href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Contact form JS-->
    <script src="~/assets/mail/jqBootstrapValidation.js"></script>
    <script src="~/assets/mail/contact_me.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
</body>
</html>

ConferenceManager/Views/Shared/_Layout.cshtml
@{
    string controller =
        ViewContext.RouteData.Values["controller"].ToString();
    string action =
        ViewContext.RouteData.Values["action"].ToString();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Conference Manager</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

    @RenderSection("scripts", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <a class="navbar-brand" href="/">ConferenceManager</a>
            <button class="navbar-toggler" type="button"
                    data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="ToggleNavigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <nav class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" asp-controller="Conference" asp-action="Dashboard">Home</a>
                    <a class="nav-item nav-link" asp-controller="Conference" asp-action="ListConferences">Conferences</a>
                    <a class="nav-item nav-link" asp-controller="Attendee" asp-action="ListAttendees">Attendees</a>
                    <a class="nav-item nav-link" asp-controller="Presentation" asp-action="ListPresentations">Presentations</a>
                    <a class="nav-item nav-link" asp-controller="Venue" asp-action="ListVenues">Venues</a>
                    <a class="nav-item nav-link" asp-controller="Room" asp-action="ListRooms">Rooms</a>
                </div>
                <div class="navbar-nav navbar-right">
                    <vc:login-logout user="@User" />
                </div>
            </nav>
        </nav>
    </header>

    <div class="row">
        <nav class="cols-2"><vc:side-nav /></nav>
        <div class="container col-8">
            <temp-message />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <div class="col-2"></div>
    </div>
    <footer class="border-top footer text-muted row">
        <div class="container">
            <vc:copyright />
        </div>
    </footer>
</body>
</html>